[profile]
input_jar = "ref/runescape.jar"
output_jar = "ref/runescape-deob.jar"
output_dir = "src/main/java"

class_deob = true
class_remap = true
class_decompile = true
java_cleanup = true

# pre-remap transformers
pre_transformers = [
    "OriginalName",
    "RedundantGoto"
]

# post-remap transformers
transformers = [
    "RedundantGoto",
    "Visibility",
    "Zwyz"
]

# post-decompilation source transformers
ast_transformers = [
    "Increment"
]

[profile.original_name]
# we produce openrs2-compatible deob annotations but since we don't have a library system
# we require the profile here to include the openrs2 library annotation. this gets prefixed
# to the class name i.e. "client!" and "loader!"
library_annotation = "client"

[profile.zwyz]
removeUnreachable = true
