[profile]
input_jar = "ref/runescape.jar"
output_jar = "ref/runescape"
output_dir = "src/main/java"

class_deob = true

# pre-remap transformers
pre_transformers = [
    "OriginalName"
]

class_remap = true
class_remap_file = "remap.txt"

# post-remap transformers
transformers = [
    "CalledMethods",
    "ErrorHandlers",
    "ParameterChecks",
    "UnreachableCode",
    "Goto",
    "StaticMethods",
    "SortMethods",
    "StaticFields",
    "SortFieldsName",
    "VariableSplitter",
    "ExpressionSorter",
    "RlMath",
    "Visibility",
]

class_decompile = true

# post-decompilation source transformers
java_cleanup = true

ast_transformers = [
    # "Unenclose",
    "NegativeLiteral",
    "Complement",
    "Not",
    # "CharLiteral", # sensitive to package visibility issues
    "IfElse",
    "Ternary",
    # "BinaryExprOrder", # sensitive to package visibility issues
    # "AddSub", # sensitive to package visibility issues
    "Identity",
    "BitMask",
    "HexLiteral",
    "ValueOf",
    "NewInstance",
    "Increment",
    "ForLoopCondition",
    # "RedundantCast", # sensitive to package visibility issues
    # "Enclose"
]
