[profile]
input_jar = "ref/runescape.jar"
output_jar = "ref/runescape"
output_dir = "src/main/java"
# default_package = "com.jagex.oldschool"

class_deob = false

# pre-remap transformers
pre_transformers = [
    "OriginalName",
    "SortClassesLegacy"
]

class_remap = false

# post-remap transformers
transformers = [
]

class_decompile = true

# post-decompilation source transformers
java_cleanup = true
ast_transformers = [
    # "Unenclose",
    "NegativeLiteral",
    "Complement",
    "Not",
    # "CharLiteral",
    "IfElse",
    "Ternary",
    # "BinaryExprOrder",
    # "AddSub",
    "Identity",
    "BitMask",
    "HexLiteral",
    "ValueOf",
    "NewInstance",
    "Increment",
    "ForLoopCondition",
    # "RedundantCast",
    # "Enclose"
]

[profile.zwyz]
full = true
math = true
