[profile]
input_jar = "ref/runescape.jar"
output_jar = "ref/runescape-deob.jar"
output_dir = "src/main/java"

class_deob = true
class_remap = true
class_decompile = true
java_cleanup = true

# pre-remap transformers
pre_transformers = [
    "OriginalName",
    "SortClassesLegacy"
]

# post-remap transformers
transformers = [
    "Visibility",
    "OpaquePredicate",
    "ExceptionTracing",
    "Monitor",
    "BitShift",
    "Goto",
    "VariableSplitter",
    "ExpressionSorter",
    "SortFieldsName"
]

# post-decompilation source transformers
ast_transformers = [
    "Unenclose",
    "NegativeLiteral",
    "Complement",
    "Not",
    "CharLiteral",
    "IfElse",
    "Ternary",
    "BinaryExprOrder",
    "AddSub",
    "Identity",
    "BitMask",
    "HexLiteral",
    "ValueOf",
    "NewInstance",
    "Increment",
    "ForLoopCondition",
    "RedundantCast",
    "Enclose"
]
