[profile]
input = "ref/innerpack.jar"

[profile.deob]
enable = true

# (post-remap) bytecode-level transformations to apply
transformers = [
    "CalledMethods",
    "ErrorHandlers",
    "ParameterChecks",
    "UnreachableCode",
    "Goto",
    "StaticMethods",
    "SortMethods",
    "StaticFields",
    "SortFieldsName",
    "VariableSplitter",
    "ExpressionSorter",
    "RlMath",
    "Visibility"
]

[profile.deob.parameter_checks]
complex = true

[profile.remap]
enable = true

# (pre-remap) bytecode-level transformations to apply
transformers = [
    "OriginalName"
]

[profile.source]
decompile = true
cleanup = true

# source-level transformations to apply
transformers = [
    # "Unenclose",
    "NegativeLiteral",
    "Complement",
    "Not",
    # "CharLiteral", # sensitive to package visibility issues
    "IfElse",
    "Ternary",
    # "BinaryExprOrder", # sensitive to package visibility issues
    # "AddSub", # sensitive to package visibility issues
    "Identity",
    "BitMask",
    "HexLiteral",
    "ValueOf",
    "NewInstance",
    "Increment",
    "ForLoopCondition",
    # "RedundantCast", # sensitive to package visibility issues
    # "Enclose"
]
